import { SesionAlternativas } from '../types'

// Banco de preguntas de alternativas TTM. Los primeros 5 son ejemplos iniciales;
// del b1 en adelante vienen del banco de preguntas (32 preguntas, con casos clínicos
// desde la b16). Para agregar más, sigue el mismo patrón.
export const alternativasTTM: SesionAlternativas = {
  id: 'alternativas-ttm',
  nombre: 'Alternativas TTM',
  objetivo: 'Reconocer y clasificar',
  preguntas: [
    {
      id: 'a1',
      enunciado: '¿Qué tipo de cartílago posee la ATM, a diferencia de la mayoría de las articulaciones sinoviales del cuerpo (que tienen cartílago hialino)?',
      opciones: ['Cartílago hialino', 'Fibrocartílago', 'Cartílago elástico', 'No posee cartílago'],
      indiceCorrecta: 1,
      explicacion: 'La ATM tiene fibrocartílago, más adaptable para su función principal (deslizamiento/roce), a diferencia del cartílago hialino de articulaciones de carga como la rodilla.',
      puntos: 2,
    },
    {
      id: 'a2',
      enunciado: 'El movimiento articular de la ATM durante la apertura bucal se caracteriza por ser:',
      opciones: ['Solo rotación', 'Solo traslación', 'Rototraslación continua', 'Deslizamiento puro sin rotación'],
      indiceCorrecta: 2,
      explicacion: 'Es un movimiento de rototraslación continua: al inicio de la apertura predomina la rotación y hacia el final predomina la traslación.',
      puntos: 2,
    },
    {
      id: 'a3',
      enunciado: '¿Cuál es la función principal de las fibras híbridas, tan abundantes en los músculos elevadores mandibulares?',
      opciones: [
        'Generar contracciones explosivas de corta duración',
        'Entregar versatilidad motora y resistencia a la fatiga',
        'Producir dolor referido hacia otras zonas',
        'No tienen una función conocida',
      ],
      indiceCorrecta: 1,
      explicacion: 'Las fibras híbridas combinan características de fibras tipo I y II, entregando versatilidad y buena resistencia a la fatiga.',
      puntos: 2,
    },
    {
      id: 'a4',
      enunciado: 'El reflejo miotático (ej. golpe en el mentón) es de carácter:',
      opciones: ['Polisináptico', 'Bisináptico', 'Monosináptico', 'Trisináptico'],
      indiceCorrecta: 2,
      explicacion: 'El reflejo miotático es monosináptico: la fibra aferente hace sinapsis directamente con la motoneurona.',
      puntos: 2,
    },
    {
      id: 'a5',
      enunciado: '¿Qué tipo de mecanorreceptor articular informa sobre las posiciones condilares extremas?',
      opciones: ['Tipo 1 capsular', 'Tipo 2 capsular', 'Tipo 3 ligamentoso', 'Corpúsculo de Pacini'],
      indiceCorrecta: 2,
      explicacion: 'Los receptores tipo 3 se ubican en los ligamentos, tienen alto umbral de excitación y adaptación lenta, e informan las posiciones condilares extremas.',
      puntos: 2,
    },
    {
      id: 'b1',
      enunciado: '¿Cuál es la función principal del disco articular de la ATM?',
      opciones: [
        'Producir líquido sinovial y limitar la retrusión mandibular',
        'Distribuir cargas, disminuir el roce, aportar estabilidad y permitir rotación y traslación coordinadas',
        'Inervar la cápsula y fijar el cráneo durante la apertura',
        'Unir permanentemente el disco a la superficie ósea temporal',
      ],
      indiceCorrecta: 1,
      explicacion: 'El disco distribuye cargas, reduce el roce, aporta estabilidad y permite la rototraslación coordinada del complejo cóndilo-disco.',
      puntos: 2,
    },
    {
      id: 'b2',
      enunciado: 'Durante la protrusión mandibular, ¿qué músculo actúa como agonista?',
      opciones: ['Temporal posterior', 'Masetero profundo', 'Pterigoideo lateral, haz inferior, bilateral', 'Digástrico'],
      indiceCorrecta: 2,
      explicacion: 'El pterigoideo lateral, haz inferior, actuando bilateralmente, es el protagonista del movimiento de protrusión.',
      puntos: 2,
    },
    {
      id: 'b3',
      enunciado: '¿Qué característica distingue funcionalmente a los músculos elevadores mandibulares?',
      opciones: [
        'Predominio exclusivo de fibras IIX para movimientos bruscos',
        'Ausencia de fibras lentas',
        'Presencia de fibras tipo I e híbridas que favorecen resistencia, control fino y adaptación al alimento',
        'Una motoneurona inerva siempre menos fibras que en el pterigoideo lateral',
      ],
      indiceCorrecta: 2,
      explicacion: 'Los elevadores combinan fibras tipo I e híbridas, lo que entrega resistencia a la fatiga y un control fino adaptado al tipo de alimento.',
      puntos: 2,
    },
    {
      id: 'b4',
      enunciado: '¿Qué receptor propioceptivo responde principalmente a la tensión generada durante la contracción muscular activa?',
      opciones: ['Huso neuromuscular', 'Órgano tendinoso de Golgi', 'Corpúsculo de Pacini', 'Termorreceptor'],
      indiceCorrecta: 1,
      explicacion: 'El órgano tendinoso de Golgi, ubicado en la unión músculo-tendinosa, sensa la tensión, tanto en contracción activa como en elongación.',
      puntos: 2,
    },
    {
      id: 'b5',
      enunciado: '¿Cuál afirmación representa el modelo de adaptación al dolor?',
      opciones: [
        'El dolor siempre aumenta la actividad de los agonistas y genera espasmo',
        'El dolor produce una respuesta protectora con movimientos más lentos y limitados',
        'El dolor muscular depende exclusivamente de la isquemia',
        'La respuesta motora es idéntica en todos los pacientes y contextos',
      ],
      indiceCorrecta: 1,
      explicacion: 'El modelo de adaptación al dolor propone que este genera una respuesta protectora del sistema motor: movimientos más lentos y limitados para favorecer la recuperación.',
      puntos: 2,
    },
    {
      id: 'b6',
      enunciado: '¿Cuál hallazgo corresponde a sensibilización central?',
      opciones: [
        'Aumento del umbral de la segunda neurona',
        'Dolor restringido obligatoriamente al tejido lesionado',
        'Descargas espontáneas y expansión de los campos receptivos',
        'Respuesta aumentada al calor como marcador central fiable',
      ],
      indiceCorrecta: 2,
      explicacion: 'La sensibilización central se caracteriza por descargas espontáneas de neuronas centrales y expansión de sus campos receptivos.',
      puntos: 2,
    },
    {
      id: 'b7',
      enunciado: 'En la cascada BDNF-TrkB-KCC2 del dolor neuropático, ¿qué ocurre con el GABA?',
      opciones: [
        'Mantiene siempre su efecto inhibitorio por entrada de cloro',
        'Pasa de inhibitorio a excitatorio por inversión del gradiente de cloro',
        'Bloquea la microglía mediante P2X4',
        'Aumenta la captación de glutamato por GLT-1',
      ],
      indiceCorrecta: 1,
      explicacion: 'El bloqueo de KCC2 invierte el gradiente de cloro, haciendo que la apertura de GABA-A despolarice en vez de inhibir la neurona.',
      puntos: 2,
    },
    {
      id: 'b8',
      enunciado: '¿Qué examen es el de elección para evaluar estructuras óseas de la ATM?',
      opciones: ['Ecografía', 'Resonancia magnética', 'CBCT', 'Actigrafía'],
      indiceCorrecta: 2,
      explicacion: 'El CBCT es el examen de elección para evaluar estructuras óseas de la ATM, mientras la RM se prefiere para tejidos blandos (disco).',
      puntos: 2,
    },
    {
      id: 'b9',
      enunciado: '¿Cuál es el signo clínico característico de un desplazamiento discal sin reducción?',
      opciones: [
        'Click temprano y retorno a la línea media',
        'Pop con apertura amplia bilateral',
        'Bloqueo cerrado, ausencia de ruido y deflexión hacia el lado afectado',
        'Dolor continuo urente en territorio V2 o V3',
      ],
      indiceCorrecta: 2,
      explicacion: 'El desplazamiento discal sin reducción se caracteriza por bloqueo cerrado, sin ruido articular, y deflexión hacia el lado afectado.',
      puntos: 2,
    },
    {
      id: 'b10',
      enunciado: '¿Qué hallazgo imagenológico pertenece a la osteoartritis de ATM?',
      opciones: [
        'Únicamente efusión sinovial',
        'Osteofitos en caras laterales o mediales del cóndilo',
        'Disco en posición normal a las 12 sin alteración ósea',
        'Aumento homogéneo obligatorio del espacio articular',
      ],
      indiceCorrecta: 1,
      explicacion: 'Los osteofitos en las caras laterales o mediales del cóndilo son un signo imagenológico característico de la osteoartritis.',
      puntos: 2,
    },
    {
      id: 'b11',
      enunciado: '¿Qué diferencia una desviación de una deflexión durante la apertura?',
      opciones: [
        'La desviación no vuelve a la línea media y la deflexión sí',
        'La desviación forma una S y vuelve a la línea media; la deflexión forma una C y no vuelve',
        'Ambas vuelven a la línea media, pero una presenta ruido',
        'La deflexión solo aparece en subluxación bilateral',
      ],
      indiceCorrecta: 1,
      explicacion: 'La desviación dibuja una S y retorna a la línea media; la deflexión dibuja una C y no retorna.',
      puntos: 2,
    },
    {
      id: 'b12',
      enunciado: '¿Cuál descripción corresponde al dolor miofascial?',
      opciones: [
        'Dolor exclusivamente articular con efusión en RM T2',
        'Puntos hipersensibles dentro de una banda tensa con posibilidad de dolor referido',
        'Acortamiento muscular indoloro y permanente por fibrosis',
        'Crisis eléctricas de segundos desencadenadas por estímulos triviales',
      ],
      indiceCorrecta: 1,
      explicacion: 'El dolor miofascial se define por puntos hipersensibles (puntos gatillo) dentro de una banda tensa muscular, con posible dolor referido.',
      puntos: 2,
    },
    {
      id: 'b13',
      enunciado: '¿Cuál rasgo es prototípico de la migraña sin aura?',
      opciones: [
        'Dolor bilateral opresivo que no empeora con actividad física',
        'Dolor unilateral habitualmente pulsátil, moderado a severo, de 4 a 72 horas y que empeora con actividad física',
        'Ataques de 1 a 600 segundos con ojo rojo y lagrimeo obligatorios',
        'Dolor occipital eléctrico reproducible al palpar el nervio',
      ],
      indiceCorrecta: 1,
      explicacion: 'La migraña sin aura es típicamente unilateral, pulsátil, de intensidad moderada a severa, dura 4-72h y empeora con la actividad física.',
      puntos: 2,
    },
    {
      id: 'b14',
      enunciado: '¿Cuál de las siguientes situaciones constituye una bandera roja de cefalea?',
      opciones: [
        'Dolor conocido reproducible al palpar el masetero',
        'Cefalea pulsátil de 4 a 72 horas sin signos neurológicos',
        'Inicio súbito en estallido',
        'Fotofobia asociada a una migraña habitual',
      ],
      indiceCorrecta: 2,
      explicacion: 'Un inicio súbito "en estallido" es una bandera roja que obliga a descartar una causa secundaria grave.',
      puntos: 2,
    },
    {
      id: 'b15',
      enunciado: '¿Cuál característica corresponde a la neuralgia trigeminal clásica?',
      opciones: [
        'Dolor continuo urente después de herpes',
        'Dolor eléctrico paroxístico unilateral, habitualmente en V2 o V3, desencadenado por estímulos triviales',
        'Dolor bilateral de más de tres meses con déficit sensorial frecuente después de una cirugía',
        'Dolor urente persistente de lengua sin lesión clínica evidente',
      ],
      indiceCorrecta: 1,
      explicacion: 'La neuralgia trigeminal clásica se caracteriza por dolor eléctrico paroxístico, unilateral, en V2 o V3, gatillado por estímulos triviales.',
      puntos: 2,
    },
    {
      id: 'b16',
      enunciado: 'Caso clínico. Una paciente presenta dolor preauricular durante la función, dolor conocido a la palpación lateral de la ATM y sin ruido articular. ¿Qué hipótesis se relaciona más directamente con el origen del dolor?',
      opciones: ['Artralgia de ATM', 'Neuralgia glosofaríngea', 'Migraña retiniana', 'Trastorno por avance de fase'],
      indiceCorrecta: 0,
      explicacion: 'El dolor preauricular que empeora con función y se reproduce en la palpación lateral de la ATM orienta a artralgia articular.',
      puntos: 2,
    },
    {
      id: 'b17',
      enunciado: 'Caso clínico. Un paciente presenta banda tensa en masetero. La palpación reproduce su dolor local y además lo proyecta hacia una zona distante. ¿Qué diagnóstico muscular es más compatible?',
      opciones: ['Co-contracción protectora', 'Dolor miofascial con dolor referido', 'Contractura mioestática indolora', 'Miositis infecciosa'],
      indiceCorrecta: 1,
      explicacion: 'La banda tensa con dolor local y dolor referido a distancia es característica del dolor miofascial.',
      puntos: 2,
    },
    {
      id: 'b18',
      enunciado: 'Caso clínico. Durante la apertura, la mandíbula sigue una trayectoria en C y no retorna a la línea media; no se detectan ruidos. ¿Qué alteración debe considerarse?',
      opciones: [
        'Desplazamiento discal sin reducción del lado hacia el cual deflecta',
        'Desplazamiento discal con reducción temprana',
        'Subluxación bilateral saludable',
        'Adherencia vencida por el movimiento',
      ],
      indiceCorrecta: 0,
      explicacion: 'La deflexión en C sin retorno, junto con ausencia de ruido, es propia del desplazamiento discal sin reducción.',
      puntos: 2,
    },
    {
      id: 'b19',
      enunciado: 'Caso clínico. Una paciente presenta dolor espontáneo, alodinia y dolor extendido más allá del tejido inicialmente afectado. ¿Qué mecanismo explica mejor el cuadro?',
      opciones: ['Aumento del umbral central', 'Sensibilización central con expansión de campos receptivos', 'Estabilidad oclusal fina', 'Reflejo miotático fásico aislado'],
      indiceCorrecta: 1,
      explicacion: 'El dolor espontáneo, la alodinia y la expansión del área dolorosa son manifestaciones de sensibilización central.',
      puntos: 2,
    },
    {
      id: 'b20',
      enunciado: 'Caso clínico. Un hombre de 22 años se duerme habitualmente a las 03:00 y despierta a las 11:00 descansado cuando puede seguir su horario, pero no logra levantarse temprano para estudiar. ¿Cuál es el diagnóstico más probable?',
      opciones: ['Insomnio crónico de conciliación', 'Trastorno por retraso de fase del sueño y del despertar', 'Trastorno por avance de fase', 'Apnea obstructiva del sueño'],
      indiceCorrecta: 1,
      explicacion: 'En el retraso de fase, el paciente duerme bien si respeta un horario desplazado hacia más tarde.',
      puntos: 2,
    },
    {
      id: 'b21',
      enunciado: 'Caso clínico. Una mujer tarda más de una hora en dormirse, cuatro noches por semana desde hace ocho meses, pese a mantener horarios regulares; presenta fatiga diurna. ¿Qué diagnóstico es más compatible?',
      opciones: ['Insomnio crónico de conciliación', 'Retraso de fase con sueño normal', 'Narcolepsia por déficit de orexinas', 'Apnea posicional confirmada'],
      indiceCorrecta: 0,
      explicacion: 'La dificultad persistente para iniciar el sueño con repercusión diurna, sin un horario desplazado, corresponde a insomnio crónico de conciliación.',
      puntos: 2,
    },
    {
      id: 'b22',
      enunciado: 'Caso clínico. Al acostarse, una paciente siente molestias desagradables en ambas piernas cuando permanece quieta y necesita caminar para aliviarlas. ¿Qué diagnóstico diferencial del insomnio de conciliación debe considerarse?',
      opciones: ['Síndrome de piernas inquietas', 'Migraña con aura', 'Hemicránea continua', 'Desplazamiento discal con reducción'],
      indiceCorrecta: 0,
      explicacion: 'Las molestias en las piernas al acostarse, aliviadas con el movimiento, son la clave del síndrome de piernas inquietas.',
      puntos: 2,
    },
    {
      id: 'b23',
      enunciado: 'Caso clínico. Un paciente presenta ronquidos, apneas presenciadas, somnolencia diurna, obesidad, cuello aumentado y retrognatia. ¿Cuál es la conducta diagnóstica correcta?',
      opciones: [
        'Confirmar AOS únicamente con STOP-Bang',
        'Diagnosticar bruxismo y prescribir un plano sin estudiar el sueño',
        'Realizar tamizaje, reconocer el alto riesgo y derivar para polisomnografía',
        'Solicitar actigrafía como examen Gold Standard de AOS',
      ],
      indiceCorrecta: 2,
      explicacion: 'Los cuestionarios solo tamizan; la polisomnografía es el Gold Standard, por lo que corresponde reconocer el alto riesgo y derivar.',
      puntos: 2,
    },
    {
      id: 'b24',
      enunciado: 'Caso clínico. En una polisomnografía se observan episodios de actividad masticatoria rítmica precedidos por activación autonómica, microdespertar y taquicardia. ¿Cómo debe interpretarse este hallazgo?',
      opciones: [
        'Como prueba de que la maloclusión causa bruxismo',
        'Como marcador de inestabilidad del sueño asociado a microdespertares',
        'Como confirmación de que el RMMA causa siempre TTM y desgaste',
        'Como una etapa normal del sueño N3 sin relación con arousals',
      ],
      indiceCorrecta: 1,
      explicacion: 'Más del 70% de los episodios de RMMA se asocian a microdespertares, por lo que se interpretan como marcador de inestabilidad del sueño.',
      puntos: 2,
    },
    {
      id: 'b25',
      enunciado: 'Caso clínico. Dos pacientes tienen el mismo desplazamiento discal con reducción. Uno presenta buen sueño y pocas comorbilidades; el otro tiene mal sueño, cefaleas y múltiples síntomas globales. Según OPPERA/ROPA, ¿quién tiene mayor riesgo?',
      opciones: [
        'El primero, porque la baja sensibilidad al dolor aumenta el riesgo',
        'El segundo, por la acumulación de predictores y un perfil de síntomas globales',
        'Ambos tienen exactamente el mismo riesgo porque comparten diagnóstico estructural',
        'No puede existir riesgo si el disco reduce',
      ],
      indiceCorrecta: 1,
      explicacion: 'El sueño, las cefaleas y los síntomas globales incrementan el riesgo; ROPA asigna mayor riesgo al cluster de síntomas globales.',
      puntos: 2,
    },
    {
      id: 'b26',
      enunciado: 'Caso clínico. Una paciente con dolor persistente interpreta cualquier molestia como señal de daño grave, piensa continuamente en el dolor y siente que nada puede hacer. ¿Qué proceso está presente?',
      opciones: [
        'Catastrofización con magnificación, rumiación y desesperanza',
        'Alexitimia limitada a dificultad para describir emociones',
        'Modulación condicionada del dolor eficiente',
        'Conducta adaptativa sin riesgo de perpetuación',
      ],
      indiceCorrecta: 0,
      explicacion: 'La catastrofización se define mediante estos tres mecanismos: magnificación, rumiación y desesperanza.',
      puntos: 2,
    },
    {
      id: 'b27',
      enunciado: 'Caso clínico. Tras una exodoncia, una paciente mantiene por más de tres meses dolor continuo y quemante en territorio V3, con alodinia e hipoestesia. ¿Qué diagnóstico es más compatible?',
      opciones: ['Neuralgia trigeminal postraumática', 'Neuralgia trigeminal clásica', 'Cefalea tensional', 'Síndrome de boca urente sin antecedente traumático'],
      indiceCorrecta: 0,
      explicacion: 'El antecedente traumático, la duración mayor a tres meses, el dolor continuo y los signos sensitivos positivos y negativos corresponden a neuralgia trigeminal postraumática.',
      puntos: 2,
    },
    {
      id: 'b28',
      enunciado: 'Caso clínico. Un paciente tiene crisis unilaterales eléctricas de uno a dos minutos en V2, provocadas al rozar una zona gatillo y sin déficit neurológico objetivo. ¿Qué diagnóstico es más probable?',
      opciones: ['Neuralgia trigeminal', 'Neuralgia postherpética', 'Dolor miofascial referido', 'Migraña crónica'],
      indiceCorrecta: 0,
      explicacion: 'La duración breve, el carácter eléctrico, el territorio trigeminal y el desencadenamiento por estímulos triviales son prototípicos de la neuralgia trigeminal.',
      puntos: 2,
    },
    {
      id: 'b29',
      enunciado: 'Caso clínico. Una cefalea unilateral orbitaria dura entre 15 y 180 minutos, es muy intensa, aparece por periodos y el paciente se muestra inquieto durante las crisis. ¿Cuál es el diagnóstico más compatible?',
      opciones: ['Cefalea en racimos', 'Hemicránea paroxística', 'SUNCT', 'Cefalea tensional'],
      indiceCorrecta: 0,
      explicacion: 'La duración de 15-180 min, el dolor orbitario intenso, el patrón periódico y la inquietud son característicos de la cefalea en racimos.',
      puntos: 2,
    },
    {
      id: 'b30',
      enunciado: 'Caso clínico. Una paciente presenta ataques unilaterales de 10 segundos, decenas de veces al día, siempre con ojo rojo y lagrimeo. ¿Qué diagnóstico corresponde?',
      opciones: ['SUNA', 'SUNCT', 'Migraña sin aura', 'Hemicránea continua'],
      indiceCorrecta: 1,
      explicacion: 'SUNCT exige la combinación de inyección conjuntival y lagrimeo, junto con ataques de 1-600 segundos.',
      puntos: 2,
    },
    {
      id: 'b31',
      enunciado: 'Caso clínico. Un estudio evalúa si una mala calidad de sueño precede y aumenta la probabilidad de desarrollar TTM en personas inicialmente sanas. ¿Qué diseño responde mejor a esa pregunta pronóstica?',
      opciones: ['Estudio transversal', 'Estudio de cohorte', 'Reporte de caso', 'Opinión de expertos'],
      indiceCorrecta: 1,
      explicacion: 'Para preguntas pronósticas se recomienda el estudio de cohorte, con medidas como riesgo relativo o supervivencia.',
      puntos: 2,
    },
    {
      id: 'b32',
      enunciado: 'Caso clínico. Un ensayo informa un RR cuyo intervalo de confianza del 95% cruza el valor 1. ¿Cómo se interpreta esto?',
      opciones: [
        'El resultado se considera estadísticamente significativo',
        'El resultado no se considera estadísticamente significativo',
        'Demuestra causalidad sin necesidad de aleatorización',
        'Indica que el NNTB es necesariamente cercano a 1',
      ],
      indiceCorrecta: 1,
      explicacion: 'Cuando el IC 95% de un OR o RR cruza el valor 1, el resultado no se considera estadísticamente significativo.',
      puntos: 2,
    },
  ],
}
