import { SesionCasosClinicos } from '../types'

// Ejemplo cargado con 3 preguntas de tu prueba acumulativa de TTM.
// Para agregar más preguntas: copia el patrón de un objeto dentro de "preguntas"
// y arma su pauta con los puntos clínicos clave que esperarías ver en una buena respuesta.
// Puedes pedirme ayuda para redactar la pauta de cualquier pregunta nueva que tengas.
export const casosClinicosTTM: SesionCasosClinicos = {
  id: 'casos-clinicos-ttm',
  nombre: 'Casos Clínicos TTM',
  objetivo: 'Evaluar hipótesis',
  preguntas: [
    {
      id: 'circulo-vicioso-fibras-hibridas',
      tema: 'control-motor',
      caso: 'La teoría clásica del "círculo vicioso" propone que una contracción muscular sostenida genera isquemia, acumulación de metabolitos y dolor, perpetuando un ciclo continuo de mayor actividad muscular.',
      pregunta: 'Utilizando los conocimientos de anatomía funcional de la musculatura mandibular, analice críticamente esta teoría. Explique la importancia funcional de las fibras híbridas en los músculos elevadores mandibulares y cómo este conocimiento contribuye a interpretar las limitaciones de este modelo para explicar el dolor muscular. (6 ptos)',
      duracionSegundos: 480, // 8 min
      pauta: [
        { id: 'c1', texto: 'Explica correctamente el modelo del círculo vicioso (contracción → isquemia → dolor → más contracción)', puntos: 1 },
        { id: 'c2', texto: 'Define qué son las fibras híbridas (combinación de características tipo I y tipo II) en los músculos elevadores', puntos: 1 },
        { id: 'c3', texto: 'Explica que las fibras híbridas están adaptadas para actividad tónica sostenida, con buena resistencia a la fatiga/isquemia', puntos: 2 },
        { id: 'c4', texto: 'Concluye que esto limita al modelo de círculo vicioso como explicación única/suficiente del dolor muscular masticatorio', puntos: 2 },
      ],
    },
    {
      id: 'oppera-factores-riesgo-asociacion',
      tema: 'metodologia-oppera',
      caso: 'En un paciente con TTM doloroso se identifican: (1) disminución del umbral de dolor a la presión, (2) mala calidad de sueño desde hace varios meses, (3) múltiples síntomas orofaciales inespecíficos previos al inicio del dolor.',
      pregunta: 'A partir de la evidencia proveniente de OPPERA, analice el significado clínico de estos tres hallazgos. Diferencie cuáles corresponden principalmente a factores de riesgo, cuáles a factores de asociación, y explique por qué esta distinción es relevante. (10 puntos)',
      duracionSegundos: 900, // 15 min
      pauta: [
        { id: 'o1', texto: 'Identifica el umbral de dolor a presión disminuido como marcador de sensibilización / factor de riesgo', puntos: 2 },
        { id: 'o2', texto: 'Identifica la mala calidad de sueño como factor de riesgo', puntos: 2 },
        { id: 'o3', texto: 'Identifica los síntomas orofaciales inespecíficos previos como factor de riesgo/predictor temprano', puntos: 2 },
        { id: 'o4', texto: 'Explica la diferencia conceptual entre factor de riesgo (precede y predice la aparición) y factor de asociación (coexiste, no necesariamente causal)', puntos: 2 },
        { id: 'o5', texto: 'Explica la relevancia clínica de esta distinción (prevención vs. manejo del cuadro ya instalado)', puntos: 2 },
      ],
    },
    {
      id: 'desplazamiento-discal-cronificacion',
      tema: 'diagnosticos-articulares',
      caso: 'Dos pacientes con el mismo diagnóstico de desplazamiento discal con reducción. El primero: previamente sano, sin dolor persistente. El segundo: insomnio crónico, migraña, cervicalgia, múltiples síntomas somáticos y varios síntomas orofaciales inespecíficos.',
      pregunta: 'Desde el modelo propuesto por OPPERA y ROPA, explique cuál paciente presenta mayor riesgo de persistencia o cronificación del dolor. Fundamente con al menos tres factores de riesgo o de asociación descritos en la evidencia. (8 puntos)',
      duracionSegundos: 720, // 12 min
      pauta: [
        { id: 'd1', texto: 'Identifica correctamente al segundo paciente como el de mayor riesgo de cronificación', puntos: 1 },
        { id: 'd2', texto: 'Menciona el insomnio crónico como factor de riesgo/asociación relevante', puntos: 2 },
        { id: 'd3', texto: 'Menciona migraña y/o cervicalgia como comorbilidades asociadas a sensibilización central', puntos: 2 },
        { id: 'd4', texto: 'Menciona los síntomas somáticos múltiples y orofaciales inespecíficos como marcadores de vulnerabilidad sistémica', puntos: 2 },
        { id: 'd5', texto: 'Fundamenta usando el modelo de vulnerabilidad multisistémica de OPPERA/ROPA', puntos: 1 },
      ],
    },
    {
      id: 'cocontraccion-protectora',
      tema: 'control-motor',
      caso: 'Paciente consulta por limitación progresiva de la apertura bucal, sin antecedente de exodoncia ni trauma reciente. Refiere que antes podía morder una manzana completa y ahora no puede. Además nota cansancio mandibular al masticar y siente que "muerde más adelante" que antes. No refiere dolor articular importante.',
      pregunta: 'Explique el mecanismo neuromuscular más probable detrás de este cuadro, fundamente por qué NO correspondería indicar toxina botulínica como primera línea, y proponga la conducta terapéutica más adecuada. (8 puntos)',
      duracionSegundos: 600, // 10 min
      pauta: [
        { id: 'p1', texto: 'Identifica el cuadro como co-contracción muscular protectora, no como hiperactividad muscular primaria', puntos: 2 },
        { id: 'p2', texto: 'Explica el mecanismo: un input nociceptivo/articular genera inhibición del músculo agonista y activación del antagonista para limitar el movimiento y proteger la estructura', puntos: 2 },
        { id: 'p3', texto: 'Explica por qué la toxina botulínica es inadecuada aquí: al paralizar el músculo protector, la articulación queda sin restricción y tiende a inflamarse con mayor intensidad', puntos: 2 },
        { id: 'p4', texto: 'Propone un manejo adecuado: buscar y tratar la noxa/causa articular subyacente con enfoque conservador, sin depender de relajante muscular ni toxina como tratamiento de la causa', puntos: 2 },
      ],
    },
    {
      id: 'cluster-oppera',
      tema: 'metodologia-oppera',
      caso: 'Dos pacientes con TTM doloroso. Paciente A: alta tolerancia al dolor a la palpación, bajo distress psicológico, poca somatización, pocas comorbilidades dolorosas. Paciente B: alta sensibilidad al dolor experimental, ansiedad, depresión, catastrofización del dolor, múltiples comorbilidades dolorosas y peor función física y mental.',
      pregunta: 'Clasifique a cada paciente según los clusters de pacientes descritos por OPPERA y fundamente qué diferencias esperaría en pronóstico y abordaje terapéutico entre ambos. (8 puntos)',
      duracionSegundos: 600, // 10 min
      pauta: [
        { id: 'k1', texto: 'Clasifica correctamente al Paciente A dentro del cluster "Adaptativos"', puntos: 2 },
        { id: 'k2', texto: 'Clasifica correctamente al Paciente B dentro del cluster "Síntomas globales"', puntos: 2 },
        { id: 'k3', texto: 'Explica que el Paciente B tiene mayor riesgo de cronificación y peor pronóstico funcional', puntos: 2 },
        { id: 'k4', texto: 'Fundamenta que el Paciente B requiere un abordaje biopsicosocial/multidisciplinario y no solo tratamiento local de la articulación o musculatura', puntos: 2 },
      ],
    },
    {
      id: 'diagnostico-articular-ruido',
      tema: 'diagnosticos-articulares',
      caso: 'Paciente refiere un click audible a los 10 mm de apertura que desaparece en el resto del recorrido, sin historia de bloqueo ni dolor articular. En el examen se logra palpar el click, y se estima que se mantiene la relación cóndilo-disco con un desplazamiento leve.',
      pregunta: 'Identifique el diagnóstico articular más probable y justifique según las características descritas, diferenciándolo de un desplazamiento discal con bloqueo intermitente. (8 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'r1', texto: 'Identifica el diagnóstico como desplazamiento discal con reducción (simple)', puntos: 2 },
        { id: 'r2', texto: 'Justifica con las características: click temprano (<30mm), se palpa, se mantiene relación cóndilo-disco con desplazamiento leve', puntos: 2 },
        { id: 'r3', texto: 'Diferencia con bloqueo intermitente: ahí habría pop/click tardío, historia de trabamiento y pérdida de relación cóndilo-disco', puntos: 2 },
        { id: 'r4', texto: 'Menciona que el bloqueo intermitente puede ser factor de riesgo de inflamación, a diferencia del desplazamiento simple', puntos: 2 },
      ],
    },
    {
      id: 'diagnostico-muscular-miofascial',
      tema: 'diagnosticos-musculares',
      caso: 'Paciente con dolor mandibular de 2 meses de evolución. Se palpa una banda tensa en el masetero derecho que, al comprimirla, reproduce dolor local pero también genera dolor referido hacia la región supraorbitaria. El dolor aumenta con la función.',
      pregunta: 'Identifique el diagnóstico muscular más probable, fundamente según el mecanismo fisiopatológico involucrado, y explique por qué NO correspondería a una mialgia local simple. (8 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'm1', texto: 'Identifica el diagnóstico como dolor miofascial', puntos: 2 },
        { id: 'm2', texto: 'Menciona la banda tensa con punto gatillo (PG) como hallazgo clave', puntos: 2 },
        { id: 'm3', texto: 'Explica el mecanismo: convergencia a nivel del SNC que genera dolor referido en un sitio distinto al origen real', puntos: 2 },
        { id: 'm4', texto: 'Diferencia de la mialgia local: en esta el dolor se mantiene localizado en el sitio de palpación, sin dolor referido', puntos: 2 },
      ],
    },
    {
      id: 'oa-bilateral-craneofacial',
      tema: 'diagnosticos-articulares',
      caso: 'Paciente con antecedente de dolor articular bilateral de larga data, actualmente sin dolor pero con crepitación ocasional. Al examen facial: mandíbula retruida, aumento del ángulo goniaco, perfil con nariz aguileña y escotadura antegonial marcada de forma bilateral.',
      pregunta: '¿Qué patología articular sugieren estos hallazgos craneofaciales? Explique el mecanismo de crecimiento facial asociado y qué tan alta es la sospecha diagnóstica según los signos descritos. (8 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'o1', texto: 'Identifica la OA bilateral como principal sospecha diagnóstica', puntos: 2 },
        { id: 'o2', texto: 'Explica el mecanismo: crecimiento rotacional posterior ("cara de portazo") asociado a reabsorción condilar progresiva', puntos: 2 },
        { id: 'o3', texto: 'Relaciona la nariz aguileña marcada con mayor probabilidad de OA', puntos: 2 },
        { id: 'o4', texto: 'Señala que la crepitación refuerza la sospecha pero que su ausencia no la descarta, y que siempre debe confirmarse con imágenes', puntos: 2 },
      ],
    },
    {
      id: 'mialgia-central-vs-periferica',
      tema: 'diagnosticos-musculares',
      caso: 'Paciente con dolor mandibular bilateral difuso de 8 meses de evolución, presente incluso en reposo, con alodinia a la palpación de múltiples músculos masticatorios y cervicales, y un dolor desproporcionado respecto a los hallazgos clínicos objetivos.',
      pregunta: 'Identifique el tipo de dolor muscular más probable y explique por qué un abordaje exclusivamente periférico (ej. bloqueos anestésicos locales) probablemente no sea efectivo, proponiendo el enfoque terapéutico más adecuado. (8 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'c1', texto: 'Identifica el cuadro como mialgia mediada centralmente (dolor muscular persistente)', puntos: 2 },
        { id: 'c2', texto: 'Menciona los hallazgos característicos: dolor difuso, bilateral, presente en reposo, alodinia, desproporción respecto a hallazgos', puntos: 2 },
        { id: 'c3', texto: 'Explica por qué el manejo periférico no basta: el origen es central, y un intento periférico podría incluso exacerbar el dolor', puntos: 2 },
        { id: 'c4', texto: 'Propone un manejo predominantemente farmacológico/centralizado, considerando comorbilidades de dolor crónico', puntos: 2 },
      ],
    },

    {
      id: 'd-estabilidad-mandibular',
      tema: 'anatomia-funcional',
      caso: '',
      pregunta: 'Analice la estabilidad mandibular integrando estabilidad oclusal, componentes articulares, posición antálgica mediada muscularmente y patología muscular. Explique por qué un cambio mandibular no debe atribuirse automáticamente a los dientes. (8 puntos)',
      duracionSegundos: 480,
      pauta: [
        { id: 'e1', texto: 'Integra la estabilidad oclusal como uno de los componentes', puntos: 1 },
        { id: 'e2', texto: 'Integra los componentes articulares', puntos: 1 },
        { id: 'e3', texto: 'Explica la posición antálgica mediada muscularmente', puntos: 2 },
        { id: 'e4', texto: 'Explica que la patología muscular suele ser secundaria y puede modificar la posición mandibular', puntos: 2 },
        { id: 'e5', texto: 'Concluye que un cambio mandibular no debe atribuirse automáticamente a los dientes', puntos: 2 },
      ],
    },
    {
      id: 'd-artrodinamia',
      tema: 'anatomia-funcional',
      caso: '',
      pregunta: 'Explique la artrodinamia de la ATM durante la apertura. Incluya la relación cóndilo-disco, la rototraslación, la presión interarticular, la lámina bilaminar y el comportamiento respecto de la eminencia en apertura máxima. (7 puntos)',
      duracionSegundos: 480,
      pauta: [
        { id: 'ar1', texto: 'Define artrodinamia como el movimiento interno del complejo cóndilo-disco', puntos: 1 },
        { id: 'ar2', texto: 'Describe la rototraslación continua', puntos: 2 },
        { id: 'ar3', texto: 'Menciona la participación de la presión interarticular', puntos: 1 },
        { id: 'ar4', texto: 'Menciona la lámina bilaminar y su rol elástico', puntos: 1 },
        { id: 'ar5', texto: 'Señala que en apertura máxima el cóndilo sobrepasa la eminencia aproximadamente 4 mm', puntos: 2 },
      ],
    },
    {
      id: 'd-circulo-vicioso-ipam',
      tema: 'control-motor',
      caso: '',
      pregunta: 'Analice críticamente la teoría del círculo vicioso utilizando la composición de fibras musculares de los elevadores mandibulares y los modelos de adaptación al dolor e IPAM. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'cv1', texto: 'Señala la escasa evidencia científica y el carácter simplista del modelo de círculo vicioso', puntos: 2 },
        { id: 'cv2', texto: 'Explica la composición de fibras tipo I e híbridas de los elevadores y su versatilidad/resistencia', puntos: 2 },
        { id: 'cv3', texto: 'Contrasta con el modelo de adaptación al dolor: respuesta protectora, movimientos más lentos y limitados', puntos: 2 },
        { id: 'cv4', texto: 'Explica el IPAM como una nueva estrategia de reclutamiento muscular', puntos: 2 },
        { id: 'cv5', texto: 'Explica la multidimensionalidad e individualidad contextual del dolor según el IPAM', puntos: 2 },
      ],
    },
    {
      id: 'd-reflejo-miotatico-nociceptivo',
      tema: 'control-motor',
      caso: '',
      pregunta: 'Compare el reflejo miotático fásico y tónico con el reflejo nociceptivo. Incluya receptor o aferencia, tipo de sinapsis, finalidad protectora y respuesta muscular. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'rm1', texto: 'Describe el reflejo miotático: husos Ia/II, monosináptico, mediado por el núcleo mesencefálico', puntos: 2 },
        { id: 'rm2', texto: 'Diferencia el fásico (preventivo, estiramiento brusco) del tónico (antigravitacional, estiramiento lento)', puntos: 2 },
        { id: 'rm3', texto: 'Describe el reflejo nociceptivo: polisináptico, mediado por aferencias nociceptivas', puntos: 2 },
        { id: 'rm4', texto: 'Explica la respuesta muscular del nociceptivo: excitación de depresores e inhibición de elevadores', puntos: 2 },
        { id: 'rm5', texto: 'Señala que el nociceptivo, a diferencia del miotático, envía información ascendente a corteza', puntos: 2 },
      ],
    },
    {
      id: 'd-nocicepcion-etapas',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Explique las etapas de la nocicepción —transducción, transmisión, modulación y percepción— y diferencie nocicepción de dolor. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'n1', texto: 'Describe la transducción: conversión del estímulo en señal eléctrica', puntos: 2 },
        { id: 'n2', texto: 'Describe la transmisión: conducción de la señal hacia el SNC', puntos: 2 },
        { id: 'n3', texto: 'Describe la modulación: aumento o disminución del impulso', puntos: 2 },
        { id: 'n4', texto: 'Describe la percepción: experiencia consciente del estímulo', puntos: 2 },
        { id: 'n5', texto: 'Diferencia nocicepción (detección/transmisión) de dolor (experiencia sensorial-emocional construida en el cerebro)', puntos: 2 },
      ],
    },
    {
      id: 'd-sensibilizacion-periferica-central',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Compare sensibilización periférica y central en cuanto a localización, cambio de umbral, mecanismos y manifestaciones clínicas. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 's1', texto: 'Ubica la sensibilización periférica en las terminales nociceptivas y sus campos receptivos', puntos: 2 },
        { id: 's2', texto: 'Explica que la periférica es impulsada por transducción/transformación', puntos: 2 },
        { id: 's3', texto: 'Ubica la sensibilización central en el SNC, por ganancia sináptica', puntos: 2 },
        { id: 's4', texto: 'Menciona el menor umbral, hiperalgesia y alodinia como manifestaciones comunes', puntos: 2 },
        { id: 's5', texto: 'Para la central, menciona las descargas espontáneas y la expansión de campos receptivos', puntos: 2 },
      ],
    },
    {
      id: 'd-microglia-astrocitos',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Describa el papel de la microglía y los astrocitos en la sensibilización central. Incluya receptores o vías y mediadores mencionados en el documento. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'mg1', texto: 'Explica la activación de la microglía por ATP/P2X4-P2X7 y LPS/TLR4', puntos: 2 },
        { id: 'mg2', texto: 'Menciona vías intracelulares involucradas: p38 MAPK, NF-kB, ERK o NLRP3', puntos: 2 },
        { id: 'mg3', texto: 'Menciona mediadores liberados por la microglía: IL-1β, TNF-α, IL-6, BDNF, ROS', puntos: 2 },
        { id: 'mg4', texto: 'Explica el rol de los astrocitos en la glutamina/glutamato y la disminución de GLT-1', puntos: 2 },
        { id: 'mg5', texto: 'Menciona la liberación de citoquinas/quimiocinas y la menor eliminación de GABA por los astrocitos', puntos: 2 },
      ],
    },
    {
      id: 'd-cascada-bdnf',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Explique paso a paso la cascada BDNF-TrkB-KCC2 y por qué produce desinhibición en dolor neuropático. (8 puntos)',
      duracionSegundos: 480,
      pauta: [
        { id: 'bd1', texto: 'Explica que P2X4-p38 activa la microglía', puntos: 1 },
        { id: 'bd2', texto: 'Explica la secreción de BDNF y su unión a TrkB', puntos: 2 },
        { id: 'bd3', texto: 'Explica el bloqueo de KCC2 y la acumulación intracelular de cloro', puntos: 2 },
        { id: 'bd4', texto: 'Explica que la apertura de GABA-A provoca salida de cloro y despolarización', puntos: 2 },
        { id: 'bd5', texto: 'Concluye que esto invierte el efecto de GABA y glicina de inhibitorio a excitatorio', puntos: 1 },
      ],
    },
    {
      id: 'd-subtipo-sensibilizacion',
      tema: 'dolor-sensibilizacion',
      caso: 'Un paciente presenta hiperalgesia mecánica localizada y alodinia dinámica, pero con modulación condicionada del dolor (CPM) conservada.',
      pregunta: 'Proponga el subtipo predominante de sensibilización central y fundamente con QST y biomarcadores descritos. (8 puntos)',
      duracionSegundos: 480,
      pauta: [
        { id: 'ss1', texto: 'Orienta el cuadro hacia un subtipo espinal / de potenciación a largo plazo (LTP)', puntos: 2 },
        { id: 'ss2', texto: 'Fundamenta con hallazgos de QST: hiperalgesia mecánica estática (pinprick) y alodinia dinámica', puntos: 2 },
        { id: 'ss3', texto: 'Explica que la CPM conservada no apoya una disfunción troncoencefálica/de control descendente', puntos: 2 },
        { id: 'ss4', texto: 'Menciona el potencial N13 como biomarcador de excitabilidad espinal', puntos: 2 },
      ],
    },
    {
      id: 'd-sensibilizacion-multinivel',
      tema: 'dolor-sensibilizacion',
      caso: 'Una paciente presenta dolor regional o generalizado, hipervigilancia, comorbilidad afectiva y CPM deficiente.',
      pregunta: 'Analice los niveles de sensibilización implicados y la lógica de un tratamiento personalizado descrita en el resumen. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'sm1', texto: 'Relaciona la CPM deficiente con una alteración de los controles descendentes troncoencefálicos', puntos: 2 },
        { id: 'sm2', texto: 'Relaciona la hipervigilancia y comorbilidad afectiva con circuitos talamocorticales', puntos: 2 },
        { id: 'sm3', texto: 'Identifica un cuadro de sensibilización central de mayor complejidad, combinando ambos niveles', puntos: 2 },
        { id: 'sm4', texto: 'Menciona la potenciación de sistemas inhibidores descendentes como parte del tratamiento', puntos: 2 },
        { id: 'sm5', texto: 'Menciona la terapia cognitivo-conductual (TCC) según el mecanismo predominante', puntos: 2 },
      ],
    },
    {
      id: 'd-comparar-desplazamientos',
      tema: 'diagnosticos-articulares',
      caso: '',
      pregunta: 'Compare el desplazamiento discal con reducción, con bloqueo intermitente y sin reducción. Incluya relación cóndilo-disco, tipo de ruido, patrón de movimiento y bloqueo. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'cd1', texto: 'Con reducción: disco desplazado que logra recapturarse, con click', puntos: 2 },
        { id: 'cd2', texto: 'Con bloqueo intermitente: pérdida de relación cóndilo-disco con dificultad de movimiento, pop o click tardío e historia de trabamiento', puntos: 3 },
        { id: 'cd3', texto: 'Sin reducción: el disco no logra recapturarse, bloqueo cerrado, sin ruido y deflexión hacia el lado afectado', puntos: 3 },
        { id: 'cd4', texto: 'Diferencia claramente el patrón de bloqueo entre las tres condiciones (intermitente vs. cerrado permanente)', puntos: 2 },
      ],
    },
    {
      id: 'd-adherencia-adhesion-subluxacion',
      tema: 'diagnosticos-articulares',
      caso: '',
      pregunta: 'Diferencie adherencia, adhesión, subluxación y luxación espontánea de ATM utilizando temporalidad o permanencia, movilidad discal, signos clínicos y tipo de bloqueo. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'aa1', texto: 'Adherencia: unión fibrosa laxa y viscosa, vencible con movimiento', puntos: 2 },
        { id: 'aa2', texto: 'Adhesión: unión fibrosa densa y fija, disco anclado, requiere confirmación con RM', puntos: 3 },
        { id: 'aa3', texto: 'Subluxación: salto articular sobre la eminencia, apertura amplia, abombamiento preauricular', puntos: 2 },
        { id: 'aa4', texto: 'Luxación espontánea: estiramiento ligamentario con bloqueo abierto que impide el cierre bucal', puntos: 3 },
      ],
    },
    {
      id: 'd-hipotesis-retrodiscitis',
      tema: 'diagnosticos-articulares',
      caso: 'Paciente presenta dolor posterior articular intenso al empujar el cóndilo hacia atrás (compresión), y efusión marcada en la zona retrodiscal en RM T2.',
      pregunta: 'Formule la hipótesis diagnóstica y explique su relación con el desplazamiento discal sin reducción. (7 puntos)',
      duracionSegundos: 480,
      pauta: [
        { id: 'hr1', texto: 'Formula la hipótesis de retrodiscitis', puntos: 2 },
        { id: 'hr2', texto: 'Explica que corresponde a inflamación de la zona retrodiscal', puntos: 2 },
        { id: 'hr3', texto: 'Relaciona con el desplazamiento discal sin reducción, ya que la zona retrodiscal queda en relación directa con el cóndilo', puntos: 2 },
        { id: 'hr4', texto: 'Menciona el dolor a la compresión y la efusión en T2 como hallazgos característicos', puntos: 1 },
      ],
    },
    {
      id: 'd-oa-proceso-dinamico',
      tema: 'diagnosticos-articulares',
      caso: '',
      pregunta: 'Analice la osteoartritis de ATM como proceso dinámico. Incluya definición, inflamación, signos clínicos, necesidad de imágenes y al menos cuatro signos imagenológicos. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'oad1', texto: 'Define la OA como un trastorno degenerativo de las superficies articulares', puntos: 2 },
        { id: 'oad2', texto: 'Explica que corresponde a osteoartrosis más sinovitis, con inflamación crónica de bajo grado', puntos: 2 },
        { id: 'oad3', texto: 'Señala que la crepitación puede o no estar presente (no es obligatoria) y que las imágenes siempre deben pedirse', puntos: 2 },
        { id: 'oad4', texto: 'Menciona al menos cuatro signos imagenológicos (reabsorción ósea, esclerosis subcortical, erosión cortical, osteofitos, pseudoquistes, cuerpos libres, alteración del trabeculado)', puntos: 4 },
      ],
    },
    {
      id: 'd-no-concluir-mas-inflamado',
      tema: 'diagnosticos-musculares',
      caso: 'Dos pacientes presentan el mismo dolor local. El paciente A mueve a velocidad media y el dolor aparece solo con función; el paciente B tiene dolor espontáneo, movimiento lento, sueño fragmentado, cefaleas y temor.',
      pregunta: 'Explique por qué no es correcto concluir solamente que el paciente B está "más inflamado". (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'ni1', texto: 'Distingue que la intensidad del dolor no equivale directamente a la carga inflamatoria', puntos: 2 },
        { id: 'ni2', texto: 'Reconoce que el Paciente A puede tener un predominio de dolor de origen periférico/local', puntos: 2 },
        { id: 'ni3', texto: 'Identifica en el Paciente B una combinación de dolor espontáneo, alteración de la modulación del dolor, factores psicosociales y sueño deficiente', puntos: 2 },
        { id: 'ni4', texto: 'Plantea la posibilidad de sensibilización central en el Paciente B, más allá de la inflamación local', puntos: 2 },
        { id: 'ni5', texto: 'Integra el concepto de respuesta adaptativa del control motor en la explicación', puntos: 2 },
      ],
    },
    {
      id: 'd-ccp-mialgia-miofascial-mioespasmo',
      tema: 'diagnosticos-musculares',
      caso: '',
      pregunta: 'Compare co-contracción protectora, mialgia local, dolor miofascial y mioespasmo según dolor en función, palpación, dolor referido y dolor espontáneo. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'cm1', texto: 'CCP: sin dolor local significativo a la palpación ni dolor referido', puntos: 2 },
        { id: 'cm2', texto: 'Mialgia local: dolor local reproducible en la palpación, sin dolor referido', puntos: 2 },
        { id: 'cm3', texto: 'Dolor miofascial: presencia de dolor referido característico además del dolor local', puntos: 2 },
        { id: 'cm4', texto: 'Mioespasmo: puede sumar dolor referido y dolor espontáneo, con mayor limitación y contracción muscular', puntos: 2 },
        { id: 'cm5', texto: 'Ordena los cuatro cuadros como una progresión de complejidad/cronicidad creciente', puntos: 2 },
      ],
    },
    {
      id: 'd-fases-migrana',
      tema: 'cefaleas-neuralgias',
      caso: '',
      pregunta: 'Describa las fases de la migraña —pródromo, aura, cefalea y posdromo— con duración, clínica y mecanismo o estructura predominante. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'fm1', texto: 'Pródromo: hasta 24h antes, relacionado con el hipotálamo', puntos: 2 },
        { id: 'fm2', texto: 'Aura: 5-60 min, déficit neurológico focal, relacionado con depresión cortical propagada (CSD)', puntos: 2 },
        { id: 'fm3', texto: 'Cefalea: 4-72h, con síntomas migrañosos característicos, mediada por el sistema trigémino-vascular y CGRP/PACAP', puntos: 3 },
        { id: 'fm4', texto: 'Posdromo: horas hasta dos días, con fatiga y dificultad cognitiva, hasta la recuperación funcional', puntos: 3 },
      ],
    },
    {
      id: 'd-cefaleas-trigemino-autonomicas',
      tema: 'cefaleas-neuralgias',
      caso: '',
      pregunta: 'Compare cefalea en racimos, hemicránea paroxística, SUNCT, SUNA y hemicránea continua considerando duración, frecuencia y rasgos diferenciadores. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'ct1', texto: 'Cefalea en racimos: 15-180 min, con inquietud durante las crisis', puntos: 2 },
        { id: 'ct2', texto: 'Hemicránea paroxística: 2-30 min, más de 5 episodios/día, con respuesta completa a indometacina', puntos: 3 },
        { id: 'ct3', texto: 'SUNCT/SUNA: 1-600 segundos, decenas a cientos de episodios/día', puntos: 2 },
        { id: 'ct4', texto: 'Diferencia SUNCT (inyección conjuntival y lagrimeo) de SUNA (solo uno de los dos signos autonómicos)', puntos: 3 },
        { id: 'ct5', texto: 'Hemicránea continua: más de 3 meses, con exacerbaciones y respuesta a indometacina', puntos: 2 },
      ],
    },
    {
      id: 'd-banderas-rojas-cefalea',
      tema: 'cefaleas-neuralgias',
      caso: '',
      pregunta: 'Nombre y explique al menos cinco banderas rojas de cefalea y señale por qué modifican el razonamiento diagnóstico. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'br1', texto: 'Nombra al menos 5 banderas rojas (inicio súbito/en estallido, cambio reciente del patrón, patrón posicional, relación con Valsalva, inmunodepresión, edad >50, neoplasia, síntomas sistémicos, embarazo/puerperio, edema de papila, signos neurológicos, neurocirugía reciente)', puntos: 5 },
        { id: 'br2', texto: 'Explica que su presencia obliga a descartar una causa secundaria del dolor', puntos: 3 },
        { id: 'br3', texto: 'Explica que modifican el razonamiento diagnóstico priorizando estudio/derivación sobre manejo sintomático', puntos: 2 },
      ],
    },
    {
      id: 'd-tipos-dolor',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Compare dolor nociceptivo, inflamatorio, neuropático y nociplástico en cuanto a lesión, umbral, dolor basal, función y sensibilización. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'td1', texto: 'Nociceptivo: sin lesión necesaria, umbral normal, función protectora, sin sensibilización', puntos: 2 },
        { id: 'td2', texto: 'Inflamatorio: lesión tisular presente, umbral alterado, dolor basal leve, con reparación y sensibilización periférica/central', puntos: 3 },
        { id: 'td3', texto: 'Neuropático: lesión del tejido neural, amplificación del dolor, dolor intenso, función no protectora', puntos: 3 },
        { id: 'td4', texto: 'Nociplástico: sin lesión demostrable, con alteración de la modulación/procesamiento del dolor', puntos: 2 },
      ],
    },
    {
      id: 'd-mecanismos-dolor-neuropatico',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Explique al menos cinco mecanismos periféricos y cinco centrales de producción del dolor neuropático. (15 puntos)',
      duracionSegundos: 900,
      pauta: [
        { id: 'mn1', texto: 'Menciona al menos 5 mecanismos periféricos (sensibilización periférica, nociceptores silentes, brote colateral/sprouting, disparos efápticos, focos ectópicos, cambio de fenotipo, axones hiperactivos)', puntos: 7 },
        { id: 'mn2', texto: 'Menciona al menos 5 mecanismos centrales (sensibilización central, wind-up, sumación temporal, sumación espacial, reorganización sináptica, pérdida de inhibición, hiperexcitabilidad)', puntos: 8 },
      ],
    },
    {
      id: 'd-neuralgia-postraumatica-implante',
      tema: 'cefaleas-neuralgias',
      caso: 'Tras la colocación de un implante, un paciente presenta dolor continuo y quemante en el territorio de V2 por más de tres meses, con alodinia e hipoestesia.',
      pregunta: 'Diferencie neuralgia trigeminal postraumática de neuralgia trigeminal clásica en este caso. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'np1', texto: 'Identifica el cuadro como neuralgia trigeminal postraumática', puntos: 2 },
        { id: 'np2', texto: 'Fundamenta con: antecedente lesional (implante), dolor continuo/mixto, más de 3 meses de evolución', puntos: 2 },
        { id: 'np3', texto: 'Menciona los signos sensitivos positivos (alodinia) y negativos (hipoestesia) característicos de la postraumática', puntos: 2 },
        { id: 'np4', texto: 'Diferencia de la clásica: crisis eléctricas breves, gatillos triviales, habitualmente sin déficit sensitivo objetivo, con conflicto neurovascular demostrable por RM', puntos: 4 },
      ],
    },
    {
      id: 'd-sunderland',
      tema: 'cefaleas-neuralgias',
      caso: '',
      pregunta: 'Explique la clasificación de Sunderland I a V y relacione cada grado con estructura lesionada, manifestación sensitiva y pronóstico de recuperación. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'su1', texto: 'Grado I: lesión de mielina (neurapraxia), sensibilidad conservada, recuperación completa', puntos: 2 },
        { id: 'su2', texto: 'Grado II: lesión axonal, hipoestesia, buena recuperación', puntos: 2 },
        { id: 'su3', texto: 'Grado III: axón + endoneuro, hipoestesia marcada, recuperación parcial', puntos: 3 },
        { id: 'su4', texto: 'Grado IV: suma lesión del perineuro, déficit importante, recuperación muy limitada/requiere cirugía', puntos: 3 },
        { id: 'su5', texto: 'Grado V: sección completa, anestesia, sin recuperación espontánea, requiere cirugía', puntos: 2 },
      ],
    },
    {
      id: 'd-pico-ebm',
      tema: 'metodologia-oppera',
      caso: '',
      pregunta: 'Diseñe una pregunta PICO para evaluar un tratamiento de TTM doloroso y describa los cinco pasos de la odontología basada en evidencia. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'pi1', texto: 'Construye una pregunta PICO completa (paciente, intervención, comparación, outcome) para un tratamiento de TTM doloroso', puntos: 4 },
        { id: 'pi2', texto: 'Paso 1 y 2: convertir la necesidad clínica en pregunta, y buscar la evidencia disponible', puntos: 2 },
        { id: 'pi3', texto: 'Paso 3: valoración crítica de validez, impacto y utilidad', puntos: 2 },
        { id: 'pi4', texto: 'Paso 4 y 5: integrar la evidencia con la pericia clínica y la realidad del paciente, y evaluar/hacer metacognición del proceso', puntos: 2 },
      ],
    },
    {
      id: 'd-asociacion-prediccion-mediacion',
      tema: 'metodologia-oppera',
      caso: '',
      pregunta: 'Analice la diferencia entre asociación, predicción y mediación en OPPERA/ROPA. Entregue un ejemplo de cada una. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'ap1', texto: 'Define asociación: coexistencia sin relación temporal ni causal necesaria, con un ejemplo (ej. sensibilidad al dolor aumentada en TTM)', puntos: 3 },
        { id: 'ap2', texto: 'Define predicción: un factor que antecede y aumenta la probabilidad de un desenlace, con un ejemplo (ej. calidad de sueño o síntomas orofaciales previos)', puntos: 4 },
        { id: 'ap3', texto: 'Define mediación: mecanismo que explica la vía causal entre dos variables, con un ejemplo (ej. el sueño aumenta el estrés y este influye en el TTM)', puntos: 3 },
      ],
    },
    {
      id: 'd-clusters-ropa-riesgo',
      tema: 'metodologia-oppera',
      caso: 'Se comparan tres pacientes según ROPA: uno adaptativo, uno sensible al dolor y uno con síntomas globales.',
      pregunta: 'Compare el riesgo de TTM de estos tres perfiles. Explique el papel de la sensibilidad al dolor, el malestar psicológico y las comorbilidades. (9 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'cr1', texto: 'Cluster adaptativo: sensibilidad al dolor y malestar psicológico bajos, riesgo mínimo de TTM', puntos: 2 },
        { id: 'cr2', texto: 'Cluster sensible al dolor: sensibilidad al dolor alta, malestar bajo a moderado, riesgo intermedio', puntos: 2 },
        { id: 'cr3', texto: 'Cluster síntomas globales: ambos factores altos, con un riesgo aproximadamente 2,8 veces mayor', puntos: 3 },
        { id: 'cr4', texto: 'Menciona que menor salud física/mental, menor variabilidad de la frecuencia cardiaca y más comorbilidades aumentan el riesgo', puntos: 2 },
      ],
    },
    {
      id: 'd-rmma-inestabilidad-sueno',
      tema: 'sueno-bruxismo',
      caso: '',
      pregunta: 'Explique por qué el bruxismo del sueño/RMMA puede considerarse un marcador de inestabilidad del sueño. Incluya secuencia fisiológica, etapas donde es más frecuente y factores asociados. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'rm1b', texto: 'Describe la secuencia fisiológica: activación autonómica, microdespertar, taquicardia, activación de suprahioideos, respiración amplia, cambios de presión arterial, RMMA y deglución', puntos: 4 },
        { id: 'rm2b', texto: 'Menciona que más del 70% de los episodios de RMMA se asocian a microdespertares', puntos: 2 },
        { id: 'rm3b', texto: 'Señala que es más frecuente en las etapas N1, N2 y en la transición NREM-REM', puntos: 2 },
        { id: 'rm4b', texto: 'Menciona factores asociados: AOS/arousals, ronquido, movimientos periódicos de extremidades, reflujo, cafeína, nicotina y ciertos fármacos', puntos: 3 },
        { id: 'rm5b', texto: 'Aclara que la maloclusión NO es un factor asociado según la evidencia', puntos: 1 },
      ],
    },
    {
      id: 'd-bruxismo-atribuido-pareja',
      tema: 'sueno-bruxismo',
      caso: 'Un paciente atribuye su dolor muscular y desgaste dentario exclusivamente al bruxismo, porque su pareja escucha rechinamiento durante la noche.',
      pregunta: 'Analice la afirmación y proponga el enfoque clínico inicial adecuado. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'ba1', texto: 'Evita establecer causalidad automática entre el bruxismo reportado y el dolor muscular/desgaste dentario', puntos: 3 },
        { id: 'ba2', texto: 'Señala que existe falta de evidencia para que el RMMA sea causa directa de dolor muscular, TTM, cefalea, desgaste o fracaso restaurador', puntos: 3 },
        { id: 'ba3', texto: 'Reconoce el reporte de la pareja como un dato posible pero no confirmatorio (no reemplaza la polisomnografía)', puntos: 2 },
        { id: 'ba4', texto: 'Propone evaluar dolor, función, factores de sueño, ronquido/AOS, microdespertares, fármacos y diagnósticos diferenciales antes de concluir', puntos: 2 },
      ],
    },
    {
      id: 'd-insomnio-retraso-spi-aos',
      tema: 'sueno-bruxismo',
      caso: '',
      pregunta: 'Compare insomnio crónico, retraso de fase, síndrome de piernas inquietas y AOS como causas o imitadores de dificultad para dormir. Incluya claves clínicas y exámenes pertinentes. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'ir1', texto: 'Insomnio crónico: dificultad para dormir incluso en horario adecuado, con fatiga e hiperactivación; manejo con TCC-I', puntos: 3 },
        { id: 'ir2', texto: 'Retraso de fase: duerme bien pero en un horario desplazado hacia más tarde; se evalúa con diario de sueño/actigrafía', puntos: 3 },
        { id: 'ir3', texto: 'Síndrome de piernas inquietas: molestias en las piernas en reposo al acostarse, que alivian con el movimiento; evaluar niveles de fierro', puntos: 3 },
        { id: 'ir4', texto: 'AOS: dificultad de mantención del sueño, ronquido/apneas presenciadas/somnolencia diurna; se confirma con polisomnografía', puntos: 3 },
      ],
    },
    {
      id: 'd-sueno-dolor-evidencia',
      tema: 'sueno-bruxismo',
      caso: 'Un paciente duerme cinco horas por noche desde hace un año y presenta dolor temporomandibular persistente.',
      pregunta: 'Fundamente por qué mejorar el sueño puede influir en el dolor, utilizando evidencia epidemiológica, experimental y neurobiológica. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'sd1', texto: 'Aporta evidencia epidemiológica: alta comorbilidad entre mal dormir y dolor orofacial (riesgo relativo reportado ~3,7)', puntos: 3 },
        { id: 'sd2', texto: 'Aporta evidencia experimental: la privación/fragmentación del sueño genera hiperalgesia, menor umbral al dolor, alodinia y menor CPM', puntos: 3 },
        { id: 'sd3', texto: 'Aporta evidencia neurobiológica: menor inhibición descendente, cambios en serotonina/dopamina/GABA/opioides, aumento de citoquinas e inflamación', puntos: 4 },
        { id: 'sd4', texto: 'Concluye que la dirección sueño→dolor es más potente que la dirección inversa', puntos: 2 },
      ],
    },
    {
      id: 'd-dimensiones-dolor',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Describa las cinco dimensiones de la experiencia del dolor: nocicepción, dolor, sufrimiento, conductas de dolor y discapacidad. Explique cómo orientan una entrevista clínica. (10 puntos)',
      duracionSegundos: 600,
      pauta: [
        { id: 'dd1', texto: 'Define nocicepción como la detección fisiológica del estímulo', puntos: 2 },
        { id: 'dd2', texto: 'Define dolor como la interpretación consciente de esa señal', puntos: 2 },
        { id: 'dd3', texto: 'Define sufrimiento como el malestar emocional asociado', puntos: 2 },
        { id: 'dd4', texto: 'Define conductas de dolor como la expresión/afrontamiento observable', puntos: 2 },
        { id: 'dd5', texto: 'Define discapacidad como el deterioro funcional resultante, y explica cómo estas dimensiones orientan la entrevista clínica', puntos: 2 },
      ],
    },
    {
      id: 'd-catastrofizacion',
      tema: 'dolor-sensibilizacion',
      caso: '',
      pregunta: 'Defina catastrofización y explique sus tres mecanismos. Luego analice cómo la evaluación psicosocial identifica factores, distingue asociación/causalidad y reconoce recursos para intervenir. (12 puntos)',
      duracionSegundos: 720,
      pauta: [
        { id: 'ca1', texto: 'Define la catastrofización como una percepción negativa y exagerada (real o anticipada) del dolor', puntos: 2 },
        { id: 'ca2', texto: 'Explica el mecanismo de rumiación', puntos: 2 },
        { id: 'ca3', texto: 'Explica el mecanismo de magnificación', puntos: 2 },
        { id: 'ca4', texto: 'Explica el mecanismo de desesperanza', puntos: 2 },
        { id: 'ca5', texto: 'Explica que la evaluación psicosocial busca identificar factores intervinientes y posibles vías causales o asociaciones', puntos: 2 },
        { id: 'ca6', texto: 'Explica que también busca detectar recursos individuales, familiares y sociales para favorecer el afrontamiento funcional', puntos: 2 },
      ],
    },
  ],
}
